### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by robrichardson13** [Thource/dude-wheres-my-stuff#4]
Not sure how to replicate this issue, but because I've been getting random Runelinte crashes I looked into my logs and saw a bunch of these errors.

In my `client.log` I see a handful of these errors all happening at the same time.

`2022-06-15 09:08:08 [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
qc: null
	at ff.v(ff.java:62)
	at fs.v(fs.java:126)
	at client.yo(client.java:51840)
	at client.getItemDefinition(client.java:4469)
	at net.runelite.client.game.ItemManager.getItemComposition(ItemManager.java:383)
	at dev.thource.runelite.dudewheresmystuff.ItemStack.populateFromComposition(ItemStack.java:113)
	at dev.thource.runelite.dudewheresmystuff.ItemStack.lambda$new$0(ItemStack.java:61)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:203)
	at client.ae(client.java:27681)
	at client.ab(client.java)
	at ap.o(ap.java:338)
	at ap.run(ap.java:317)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at fs.v(fs.java:94)
	... 13 common frames omitted`

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/9492530/173988086-89a72d80-7fc2-48ac-aeb0-40f23fd07445.png">

**Comment by Thource** [comment]
I think this is fixed now, please reopen the issue if it comes back

**Comment by Thource** [comment]
Fixed in https://github.com/runelite/plugin-hub/pull/3533
